### ISSUE TITLE
View Cart button closes the view-cart-window

### ISSUE THREAD

**Issue by AnnotatedJS** [tlimpanont/simple-redux-saga-shop#1]
View Cart button closes the view-cart-window, that's inconsistent
![simple react redux saga shop example 1](https://user-images.githubusercontent.com/11474975/31563402-3370ad74-b05f-11e7-99db-467a00ee3acb.png)

**Comment by tlimpanont** [comment]
please make a PR for me!

**Comment by AnnotatedJS** [comment]
Tried but not authorized?

 % git push -u origin fix-close-cart-view   
Username for 'https://github.com': xxxxxxxxxxxxxxxxxx
Password for 'https://xxxxxxxxxxxxxxxxxxx@github.com': 
remote: Permission to tlimpanont/simple-redux-saga-shop.git denied to AnnotatedJS.
fatal: unable to access 'https://github.com/tlimpanont/simple-redux-saga-shop.git/': The requested URL returned error: 403

**Comment by tlimpanont** [comment]
Off course you cannot push it directly to my repo. That would be a major problem if anyone can destroy my code ;). You have to fork it and make the change there
