### ISSUE TITLE
On FF the right corner close text not good aligned

### ISSUE THREAD

**Issue by AnnotatedJS** [tlimpanont/simple-redux-saga-shop#2]
On FF the right corner close text not good aligned.
![simple react redux saga shop example](https://user-images.githubusercontent.com/11474975/31563681-6f1a938e-b060-11e7-9796-7fe574c4f379.png)

**Comment by tlimpanont** [comment]
whats your browser you're using?

**Comment by tlimpanont** [comment]
ahhh i see, never mind it's just an example. Don't be to hard on it, never tend to be production app. But thanks anyway

**Comment by tlimpanont** [comment]
by the way i use http://www.material-ui.com/#/. It think you should see that problem there to?
